spring.application.name=hydrata

# Banco de Dados Oracle 19c
spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=rm566234
spring.datasource.password=041005
spring.datasource.hikari.maximum-pool-size=1
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# JWT
jwt.secret=${JWT_SECRET:hydrata-secret-key-2024-fiap-2tdspv-very-long-secret}
jwt.expiration=86400000

# MQTT
mqtt.broker.url=ssl://2585265c020e418ba116d2601017a480.s1.eu.hivemq.cloud:8883
mqtt.client.id=hydrata-java-api
mqtt.username=vitalis
mqtt.password=Vitalis1

# Scheduler
scheduler.irrigacao.intervalo=30000

# Open-Meteo
openmeteo.base-url=https://api.open-meteo.com/v1

# Logging
logging.level.org.springframework.integration=DEBUG
