spring.application.name=hydrata

# Banco de Dados Oracle 19c
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# JWT
jwt.secret=${JWT_SECRET:hydrata-secret-key-2024-fiap-2tdspv-very-long-secret}
jwt.expiration=86400000

# MQTT
mqtt.broker.url=tcp://broker.mqtt.cool:1883
mqtt.client.id=hydrata-java-api

# Scheduler
scheduler.irrigacao.intervalo=300000

# Open-Meteo
openmeteo.base-url=https://api.open-meteo.com/v1
